package game;

public class about {

    static String STAR = "\u2605";

    public String help = 
    "\n\nWelcome to the game of Rock, Paper, Scissor(, Lizard, Spock)\n"
    + "Types:\n"
    + "1) Rock, Paper, Scissor\n"
    + "2) Rock, Paper, Scissor, Lizard, Spock\n"
    + "\n"
    + "\n"
    + "Levels: each type of game has 6 levels (total: 12)\n"
    + "1) Everything is possiable(none)-\n"
    + "you have 100% win guarantee\n"
    + STAR + " [Winning strategy] - spam however you like :)\n"
    + STAR + " [Losing strategy] - range quit\n"
    + "\n"
    + "2) Careless(ai) - \n"
    + "the ai is very weak, you can easily win againt it\n"
    + STAR + " [Winning strategy] - avoid switching weapons\n"
    + STAR + " [Losing strategy] - switching weapons everytime\n"
    + "\n"
    + "3) Pure Luck(random) - \n"
    + "you have 50 50 chance of Winning\n"
    + STAR + " [Winning strategy] - spamming\n"
    + STAR + " [Losing strategy] - spamming as well\n"
    + "\n"
    + "4) Tricky (ai) - \n"
    + "the ai is \"pretty\" smart, you have less chance of Winning againt it \n"
    + STAR + " [Winning strategy] - avoid going for same weapon in a row\n"
    + STAR + " [Losing strategy] - spam the same weapon multiple times in a row\n"
    + "\n"
    + "5) Dr. Tricky (ai)- \n"
    + "the ai is smart, ai knows human physiology!. you have very less chance of Winning againt it\n"
    + STAR + " [Winning strategy] - spam random weapons, just spam! NO THINKING\n"
    + STAR + " [Losing strategy] - spam the same weapon multiple times in a row\n"
    + "\n"
    + "6) Everthing is impossiable - \n"
    + "you have ZER\"0\"% chance of Winning\n"
    + STAR + "[Winning strategy] - change the code\n"
    + STAR + "[Losing strategy] - JUST SPAM!\n"
    + "\n"
    + STAR + STAR + STAR + " NOTE: avoid going small points game(like first to 3, 5 etc...) while playing againt ai.\n"
    + "\n"
    + "\n"
    + "how does the ai works:(this Ai is NOT good againt SPAMMING, to have a fair play, avoid CRAZY SPAMMING)\n"
    + "Step 1) ai collects some data from the player\n"
    + "Step 2) ai looks for what type of player you are (repeating player or alternative player)\n"
    + "Step 3) ai splits its calculations by two(one for alternative play, another for repeating play)\n"
    + "Step 4) ai changes/balaces the weapon chances(%) dependes on the playing style \n"
    + "Step 5) output the weapon by %\n"
    + "\n"
    + STAR + STAR + " Ai has a feature called \"confident level\" It helps the ai to quicky changes and adopts to player's playing style\n"
    + "For example: players goes paper, paper, paper for 10-20 times in a row... then changes weapon quicky and start beating the ai\n"
    + "\n"
    + STAR + STAR + " Ai has an another feature called \"forget value\" It helps the ai to forget old players data so the ai could perform better\n"
    + "\n"
    + "Ai(level 5) about human physiology\n"
    + STAR + " if you win... next round play what your opponent played\n"
    + STAR + " if tie... next round play randomly\n"
    + STAR + " if you lose... next round play the weapon that didn't played(for example: if ai plays ROCK, and I play SCISSOR... then play SCISSOR\n"
    + "\n"
    + "\n"
    + "After choosing what level to play, you need to select the score to win\n"
    + "\n"
    + "\n"
    + "the winner receives a gift (loser too)\n"
    + "\n"
    + "Have fun playing it! Good luck :)\n"
    + "\n"
    + "\n";
}